runtime: python27
api_version: 1
threadsafe : true

handlers:

- url: /
  static_files: static/index.htm
  upload: static/index.htm

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.*.(gif|png|jpg))
  static_files: static/\1
  upload: static/(.*\.*.(gif|png|jpg))

- url: /(.*\.*.(js))
  static_files: static/\1
  upload: static/(.*\.*.(js))

- url: /(.*\.*.(rar|zip))
  static_files: static/\1
  upload: static/(.*\.*.(rar|zip))

- url: /(.*\.*.(htm|css|woff))
  static_files: static/\1
  upload: static/(.*\.*.(htm|css|woff))


   
